// Generated by scripts/build-sw.mjs — do not edit.
const PRECACHE = {"version":"e96d7e7327","pyodideVersion":"314.0.7","bytes":22614836,"app":["./","app.js","editor.js","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512-maskable.png","icons/icon-512.png","index.html","lessons.json","manifest.webmanifest","runner.py","streak.js","styles.css","worker.js","precache.js"],"pyodide":["pyodide/numpy-2.4.6-cp314-cp314-pyemscripten_2026_0_wasm32.whl","pyodide/pandas-3.0.2-cp314-cp314-pyemscripten_2026_0_wasm32.whl","pyodide/pyodide-lock.json","pyodide/pyodide.asm.mjs","pyodide/pyodide.asm.wasm","pyodide/pyodide.js","pyodide/pyodide.mjs","pyodide/python_dateutil-2.9.0.post0-py2.py3-none-any.whl","pyodide/python_stdlib.zip","pyodide/pytz-2026.1.post1-py2.py3-none-any.whl","pyodide/six-1.17.0-py2.py3-none-any.whl"]};
const APP = "ppr-app-" + PRECACHE.version, PYO = "ppr-pyodide-" + PRECACHE.pyodideVersion;
self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    // Pyodide runtime + wheels live in a version-pinned cache so lesson updates don't re-download ~20 MB.
    const pc = await caches.open(PYO);
    await Promise.all(PRECACHE.pyodide.map(async (u) => { if (!(await pc.match(u))) await pc.add(new Request(u, { cache: "reload" })); }));
    const ac = await caches.open(APP);
    await ac.addAll(PRECACHE.app.map(u => new Request(u, { cache: "reload" })));
    // First install: take control right away. Updates wait until the user taps "Update" (see message handler),
    // so a running page never has its cached files swapped underneath it. If any download fails, install
    // rejects and the previous version keeps working untouched.
    if (!self.registration.active) await self.skipWaiting();
  })());
});
self.addEventListener("message", (e) => { if (e.data === "skipWaiting") self.skipWaiting(); });
self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith("ppr-") && k !== APP && k !== PYO) await caches.delete(k);
    await self.clients.claim();
  })());
});
self.addEventListener("fetch", (e) => {
  const req = e.request; const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;
  e.respondWith((async () => {
    if (req.mode === "navigate") {
      const shell = await caches.match(new URL("./", self.registration.scope).href);
      if (shell) return shell;
    }
    const hit = await caches.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try { return await fetch(req); } catch (err) { return new Response("Offline and not cached", { status: 503 }); }
  })());
});
