import fs from "fs"; import path from "path"; import crypto from "crypto";
const root = "public";
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]);
const files = walk(root).map(f => path.relative(root, f).split(path.sep).join("/"))
  .filter(f => !["sw.js", "precache.js", ".nojekyll"].includes(f) && !f.startsWith("screens") && !f.endsWith(".map"));
const pyodide = files.filter(f => f.startsWith("pyodide/")).sort();
const app = ["./", ...files.filter(f => !f.startsWith("pyodide/")).sort(), "precache.js"];
const h = crypto.createHash("sha256"); let bytes = 0;
for (const f of files.sort()) { const b = fs.readFileSync(path.join(root, f)); h.update(f); h.update(b); bytes += b.length; }
const pyodideVersion = JSON.parse(fs.readFileSync("node_modules/pyodide/package.json")).version;
const PRECACHE = { version: h.digest("hex").slice(0, 10), pyodideVersion, bytes, app, pyodide };
fs.writeFileSync(path.join(root, "precache.js"), `self.PRECACHE = ${JSON.stringify(PRECACHE)};\n`);
const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const PRECACHE = ${JSON.stringify(PRECACHE)};
const APP = "ppr-app-" + PRECACHE.version, PYO = "ppr-pyodide-" + PRECACHE.pyodideVersion;
self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    // Pyodide runtime + wheels live in a version-pinned cache so lesson updates don't re-download ~20 MB.
    const pc = await caches.open(PYO);
    await Promise.all(PRECACHE.pyodide.map(async (u) => { if (!(await pc.match(u))) await pc.add(new Request(u, { cache: "reload" })); }));
    const ac = await caches.open(APP);
    await ac.addAll(PRECACHE.app.map(u => new Request(u, { cache: "reload" })));
    // First install: take control right away. Updates wait until the user taps "Update" (see message handler),
    // so a running page never has its cached files swapped underneath it. If any download fails, install
    // rejects and the previous version keeps working untouched.
    if (!self.registration.active) await self.skipWaiting();
  })());
});
self.addEventListener("message", (e) => { if (e.data === "skipWaiting") self.skipWaiting(); });
self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith("ppr-") && k !== APP && k !== PYO) await caches.delete(k);
    await self.clients.claim();
  })());
});
self.addEventListener("fetch", (e) => {
  const req = e.request; const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;
  e.respondWith((async () => {
    if (req.mode === "navigate") {
      const shell = await caches.match(new URL("./", self.registration.scope).href);
      if (shell) return shell;
    }
    const hit = await caches.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try { return await fetch(req); } catch (err) { return new Response("Offline and not cached", { status: 503 }); }
  })());
});
`;
fs.writeFileSync(path.join(root, "sw.js"), sw);
fs.writeFileSync(path.join(root, ".nojekyll"), "");
console.log(`precache: ${app.length} app + ${pyodide.length} pyodide files, ${(bytes / 1e6).toFixed(1)} MB, version ${PRECACHE.version}`);
